### ISSUE TITLE
Transaction bug

### ISSUE THREAD

**Issue by abweb** [craftcoin/craftcoin#12]
Hi,

I found the bug of transactions. I send money from account a1 and this transaction contains fee. In spite of that I have not enought money for fee, money are sending. As a result balance is minus.

```
craftcoind listaccounts
{
   "" : 0.60400001,
    "a1" : 0.00000000,
    "a2" : 0.10000000,
    "a3" : 11.23506502

}
```

```
craftcoind sendfrom "a2" Q7GWriHHZ396qgtV3yiRaun1kMprBPL4mF 0.1
```

```
{
        {
        "account" : "a2",
        "address" : "Q7GWriHHZ396qgtV3yiRaun1kMprBPL4mF",
        "category" : "send",
        "amount" : -0.10000000,
        "fee" : -0.10000000,
        "confirmations" : 0,
        "txid" : "fd54d824b8a3afc412f707254f33e3cf97eec39dfc13280d2cbd9d130b32d860",
        "time" : 1388677902
    }

    }
```

```
craftcoind listaccounts
{
    "" : 0.60400001,
    "a1" : 0.00000000,
    "a2" : -0.10000000,
    "a3" : 11.23506502

}
```

**Comment by CatmanIX** [comment]
Interesting, I'll have to take a look at that.

**Comment by Sithra** [comment]
I also have a problem sending from the wallet as it seems to generate a random high transaction fee
i.e. Trying to send 9.0 Craftcoins the fee varies from 5.0 - 5.6 craftcoins?

**Comment by nicoschtein** [comment]
Hi that is not an issue, the total amount of coins in the wallet is
correct, you have negative balance in an account but the total balance of
the wallet, check getinfo is ok.

2014-02-18 23:12 GMT-03:00 Sithra notifications@github.com:
