### ISSUE TITLE
Recent Fork/Rules change

### ISSUE THREAD

**Issue by TierNolan** [craftcoin/craftcoin#14]
There wasn't much advertising about the rules change.

Was it the intention that the new rules actually be used?  There is no windows executable on the website either.

Cryptsy is still on the old rules, so they need to be notified or they could get hit with a double spending attack.

**Comment by CatmanIX** [comment]
blindmice asked me to do the changes and i compiled and sent it to him to distribute and he never did anything with it =\

Not sure what happened myself, haven't heard a word from him since.

**Comment by TierNolan** [comment]
He probably intended the old version to remain in effect then?

**Comment by TierNolan** [comment]
It is probably worth commenting on the CRC thread on bitcointalk then

**Comment by nicoschtein** [comment]
There was a post on Ann thread stating the changes so I must say that the dev intended to use them.

**Comment by TierNolan** [comment]
Which announcement thread?  The first post on the bitcointalk has nothing.

**Comment by nicoschtein** [comment]
The first post is from a user that has not been active since october 2013, so it is all outdated.
The post i am referring to was on page 34 or 35 but was has been removed or edited, it must have been before post number 697 because from there on pools and p2pool source started to be updated.
