### ISSUE TITLE
No central mining pool

### ISSUE THREAD

**Issue by CliffracerX** [craftcoin/craftcoin#15]
I love the idea, but as of right now it's really hard to get CraftCoin.

1 client probably cannot make much progress, and there are no servers in the partners list on the site, meaning no good way to get CraftCoin.  :frowning:

**Comment by nicoschtein** [comment]
Hi!
You could join http://crc.minar.cc if you'd like.

2014-02-11 13:18 GMT-03:00 Cliffie notifications@github.com:

**Comment by CliffracerX** [comment]
Ah, cool.

They should probably put that on the site or in the README.

**Comment by CatmanIX** [comment]
Mining pools are listed in the first two posts on the [BTCTalk page](https://bitcointalk.org/index.php?topic=250343.0).

**Comment by nicoschtein** [comment]
Those posts are outdated, software  version, specs and links for both pool and services...

If you have access to edit those please do.

**Comment by CatmanIX** [comment]
I can only edit the second post on the BTCTalk forums, but nothing else. I have no idea where blindmice has gone so I'm trying not to do anything 'till i hear back from him. It's his coin, I just did the graphics and some fixes >_>
