### ISSUE TITLE
Transaction issue

### ISSUE THREAD

**Issue by Gargo** [craftcoin/craftcoin#17]
Problem with transaction:
07a2a33e4f0fdbd9d63aed1221e54cd7e8c8c799937d5002201a89db6e445f57

It is a transfer from one exchange to another one. Who caused this problem? The first exchange, the second one or is it problem of CRC?

**Comment by Thomas-JP** [comment]
Hi Is The Coin Still a Live ?
If So Can You Up Date The Links For This Coin On The http://craftcoin.net
Been Trying to Find Same one with The Wallet But No Luck Plz Add a New Link For It At http://craftcoin.net plz Thanks for you time
