### ISSUE TITLE
No Link For DownLoading The Wallet Or Server Files

### ISSUE THREAD

**Issue by Thomas-JP** [craftcoin/craftcoin#18]
Hi i like To Get The Carft Coin Wallet + Bukkit Server File For This Coin.
But All Links http://craftcoin.net are Not Working Can You Fix Them & Tell us What is New In the UpDate if any ?

Will It Work With Bukkit & mcpc-plus? 1.7.9

**Comment by CatmanIX** [comment]
The original dev dumped it on me awhile ago, but he's the only one with access to the site.

I've been to sick and too busy with other things to try and get this shit put back together, so consider it a zombie for now.

I don't even know how to update the bukkit plugin to begin with, so I'm going to have to find someone else to do that. Probably be awhile before this really any useful again, if I ever even bother. It was inherently flawed to begin with.

**Comment by trismegistis** [comment]
Hi these coins still have value of over a hundred satoshi each. Is there not a way to get a  wallet at least to try and trade them?

**Comment by CatmanIX** [comment]
They shouldn't have any value, they're completely abandoned, their original intention isn't even viable anymore, the network is broken as fuck, they are literally garbage. I have no idea how or why anyone's even trying to trade them anymore.

**Comment by trismegistis** [comment]
Www.cryptsy.com look up craft coin there lol not a bad price!
