### ISSUE TITLE
Main website seems to be down.

### ISSUE THREAD

**Issue by MikeyCarter** [craftcoin/craftcoin#20]
Can't seem to connect to the network and the main website appears to be down.  Is this project dead?

**Comment by CartmanSPC** [comment]
Blockchain still going with about 300 Mh/s at the moment.

**Comment by CatmanIX** [comment]
Whatever's keeping this coin alive I have no idea, but the guy who created it dumped it on me out of the blue at the worst time possible so I just abandoned it. It was broken from the start and i couldn't be arsed to try and fix it when i didn't even have control over the website or any official announcement channels to try and control updates anyway (nor any java dev experience to get the minecraft plugin parts working).

The whole concept is pretty much forbidden by minecrafts new ToS anyway, so it's not even viable for it's intended purpose anymore. Best to just dump it and move on.
