### ISSUE TITLE
CRC is an algorithm for checking file integrity.

### ISSUE THREAD

**Issue by CatmanIX** [craftcoin/craftcoin#3]
You might wanna rethink the abbreviation, perhaps CFC or CTC? Maybe just CFT?

**Comment by craftcoin** [comment]
It's kindof an inside joke with the guy helping me. Cycle Redundancy Check coin. Tacky yes, but fun none the less.

**Comment by craftcoin** [comment]
We did consider CFC, but we were afraid the EPA would ban it
